# -*- coding: utf-8 -*-

# Copyright (c) 2025 Red Hat, Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# @generated
# This file is auto-generated by tools/generate_modules.py
# Extend with additional test cases as needed.

from __future__ import absolute_import, division, print_function

__metaclass__ = type

from unittest.mock import MagicMock

import pytest

MOCK_VAULT_CLIENT = "ansible_collections.hashicorp.vault.plugins.plugin_utils.vault_action_base.VaultClient"


@pytest.fixture
def action_module():
    """Create an instance of the action plugin with mocked Ansible internals."""
    from ansible_collections.hashicorp.vault.plugins.action.vault_database_rotate_root import ActionModule

    task = MagicMock()
    task.action = "hashicorp.vault.vault_database_rotate_root"
    task.args = {
        "url": "https://vault.example.com:8200",
        "namespace": "admin",
        "auth_method": "token",
        "token": "hvs.test-token",
    }
    connection = MagicMock()
    play_context = MagicMock()
    loader = MagicMock()
    templar = MagicMock()
    shared_loader_obj = MagicMock()

    action = ActionModule(
        task=task,
        connection=connection,
        play_context=play_context,
        loader=loader,
        templar=templar,
        shared_loader_obj=shared_loader_obj,
    )
    return action, task


class TestActionModule:
    """Tests for vault_database_rotate_root action plugin."""

    def test_operation_defined(self, action_module):
        """Verify the action plugin has an operation configured."""
        action, _task = action_module
        if hasattr(action, "OPERATION") and action.OPERATION is not None:
            assert action.OPERATION.method == "POST"
            assert "v1/{mount_path}/rotate-root/{name}" in action.OPERATION.path
        elif hasattr(action, "OPERATIONS") and action.OPERATIONS is not None:
            assert len(action.OPERATIONS) > 0
        else:
            pytest.fail("ActionModule must define OPERATION or OPERATIONS")
