---
# vars_files: [vars.yml]
#
# name: test-pki-role
# mount_path: pki
# config:
#   allowed_domains: ["example.com"]
#   allow_subdomains: true
#   max_ttl: "72h"

- name: Read or list Vault PKI roles
  hashicorp.vault.vault_pki_role_info:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    mount_path: "{{ mount_path }}"
    name: "{{ name }}"
  register: result

- name: Verify return matches contract
  ansible.builtin.assert:
    that:
      - result is not changed
      - (config | hashicorp.vault.vault_config_match(result.data)).match
    fail_msg: "Contract violation: {{ (config | hashicorp.vault.vault_config_match(result.data)).mismatches | to_json }}"
