---
- name: Manage Vault auth methods (absent)
  hashicorp.vault.vault_auth_method:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    state: absent
    path: "{{ auth_path }}"
  register: result

- name: Verify result
  ansible.builtin.assert:
    that:
      - result is not failed
