---
# @hand-crafted
- name: Cleanup - vault_database_static_role_info
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/examples/vault_database_static_role_info/vars.yml"
  tasks:
    - name: Delete test static role
      ansible.builtin.uri:
        url: "{{ vault_addr }}/v1/{{ mount_path }}/static-roles/{{ name }}"
        method: DELETE
        headers:
          X-Vault-Token: "{{ vault_token }}"
        status_code: [200, 204, 404]
