---
- name: Manage HashiCorp Vault Enterprise namespaces (present)
  hashicorp.vault.vault_namespace:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    state: present
    path: userpass
  register: result

- name: Verify result
  ansible.builtin.assert:
    that:
      - result is changed
