---
# @hand-crafted
- name: Converge - vault_database_role_info
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/examples/vault_database_role_info/vars.yml"
  tasks:
    - name: Create prerequisite dynamic role
      ansible.builtin.uri:
        url: "{{ vault_addr }}/v1/{{ mount_path }}/roles/{{ name }}"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_token }}"
        body_format: json
        body:
          db_name: "{{ config.db_name }}"
          creation_statements: "{{ config.creation_statements }}"
          default_ttl: "{{ config.default_ttl }}"
          max_ttl: "{{ config.max_ttl }}"
        status_code: [200, 204]

    - name: Include example tasks
      ansible.builtin.include_tasks:
        file: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/examples/vault_database_role_info/info.yml"
