# -*- coding: utf-8 -*-

# Copyright (c) 2025 Red Hat, Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# @generated
# This file is auto-generated by tools/generate_modules.py
# Do not edit manually -- re-run the generator instead.

from __future__ import absolute_import, division, print_function

__metaclass__ = type

from ansible_collections.hashicorp.vault.plugins.plugin_utils.generated.token import (
    TokenWriteRoleRequest,
)
from ansible_collections.hashicorp.vault.plugins.plugin_utils.operation import Operation
from ansible_collections.hashicorp.vault.plugins.plugin_utils.vault_action_base import VaultActionBase


class ActionModule(VaultActionBase):
    """Manage Vault token roles."""

    OPERATIONS = {
        "present": Operation("POST", "v1/auth/token/roles/{role_name}", TokenWriteRoleRequest),
        "read": Operation("GET", "v1/auth/token/roles/{role_name}", None),
        "absent": Operation("DELETE", "v1/auth/token/roles/{role_name}", None),
    }
