# -*- coding: utf-8 -*-

# Copyright (c) 2025 Red Hat, Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# @generated
# This file is auto-generated by tools/generate_modules.py
# Do not edit manually -- re-run the generator instead.
# TODO: update from captured OpenAPI spec when database engine paths are available

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: vault_database_creds
short_description: Generate dynamic database credentials
description:
  - Generate dynamic database credentials using the Vault HTTP API.
version_added: "2.0.0"
author:
  - Bradley Thornton (@cidrblock)
extends_documentation_fragment:
  - hashicorp.vault.vault_auth.modules
options:
    role_name:
      description: Name of the database role
      type: str
      required: true
    mount_path:
      description: Mount path of the database secrets engine
      type: str
      default: database
"""

EXAMPLES = """
# vars_files: [vars.yml]
#
# role_name: test-role
#
# expected_response_keys:
#   - username
#   - password

- name: Generate dynamic database credentials
  hashicorp.vault.vault_database_creds:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    mount_path: "{{ mount_path }}"
    role_name: "{{ role_name }}"
  register: result

- name: Verify expected keys in response
  ansible.builtin.assert:
    that:
      - result is not changed
      - result.data is defined
      - item in result.data
    fail_msg: "Missing key {{ item }} in result.data"
  loop: "{{ expected_response_keys }}"
  loop_control:
    label: "{{ item }}"
"""

RETURN = """
data:
  description: >-
    Extracted payload from the Vault C(data) response envelope.
    Validated against the module argspec at runtime.
  returned: success
  type: dict
  contains:
    username:
      description: The dynamically generated database username
      type: str
      returned: success
    password:
      description: The dynamically generated database password
      type: str
      returned: success
raw:
  description: The full JSON response from Vault including the envelope.
  returned: success
  type: dict
"""
