# -*- coding: utf-8 -*-

# Copyright (c) 2025 Red Hat, Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# @generated
# This file is auto-generated by tools/generate_modules.py
# Do not edit manually -- re-run the generator instead.
# TODO: update from captured OpenAPI spec when database engine paths are available

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: vault_pki_cert_info
short_description: Read a PKI certificate by serial number
description:
  - Read a PKI certificate by serial number using the Vault HTTP API.
version_added: "2.0.0"
author:
  - HashiCorp Vault Collection Contributors
extends_documentation_fragment:
  - hashicorp.vault.vault_auth
options:
    serial:
      description: Serial number of the certificate to read
      type: str
      required: true
    mount_path:
      description: Mount path of the PKI secrets engine
      type: str
      default: pki
"""

EXAMPLES = """
# vars_files: [vars.yml]
#
# expected_response_keys:
#   - certificate

- name: Read a PKI certificate by serial number
  hashicorp.vault.vault_pki_cert_info:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    mount_path: "{{ mount_path }}"
    serial: "{{ test_cert_serial }}"
  register: result

- name: Verify expected keys in response
  ansible.builtin.assert:
    that:
      - result is not changed
      - result.data is defined
      - item in result.data
    fail_msg: "Missing key {{ item }} in result.data"
  loop: "{{ expected_response_keys }}"
  loop_control:
    label: "{{ item }}"
"""

RETURN = """
data:
  description: >-
    Extracted payload from the Vault response envelope. Contains the
    resource fields from the C(data) or C(auth) key of the API response.
    Validated against the module argspec at runtime.
  returned: success
  type: dict
raw:
  description: The full JSON response from Vault including the envelope.
  returned: success
  type: dict
"""
