# -*- coding: utf-8 -*-

# Copyright (c) 2025 Red Hat, Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# @generated
# This file is auto-generated by tools/generate_modules.py
# Do not edit manually -- re-run the generator instead.

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: vault_token_create
short_description: Create a new Vault token
description:
  - Create a new Vault token using the Vault HTTP API.
version_added: "2.0.0"
author:
  - HashiCorp Vault Collection Contributors
extends_documentation_fragment:
  - hashicorp.vault.vault_auth.modules
options:
    display_name:
      description: Name to associate with this token
      type: str
    entity_alias:
      description: Name of the entity alias to associate with this token
      type: str
    explicit_max_ttl:
      description: Explicit Max TTL of this token
      type: str
    id:
      description: Value for the token
      type: str
    meta:
      description: Arbitrary key=value metadata to associate with the token
      type: dict
    no_default_policy:
      description: Do not include default policy for this token
      type: bool
    no_parent:
      description: Create the token with no parent
      type: bool
    num_uses:
      description: Max number of uses for this token
      type: int
    period:
      description: Renew period
      type: str
    policies:
      description: List of policies for the token
      type: list
      elements: str
    renewable:
      description:
        - Allow token to be renewed past its initial TTL up to
        - system/mount maximum TTL
      type: bool
      default: true
    ttl:
      description: Time to live for this token
      type: str
    type:
      description: Token type
      type: str
"""

EXAMPLES = """
# vars_files: [vars.yml]
#
# params:
#   display_name: my-service-token
#   renewable: true
#   policies: ["default"]
#   num_uses: 10
#
# expected_response_keys:
#   - client_token
#   - accessor
#   - policies
#   - renewable
#   - token_type

- name: Create a new Vault token
  hashicorp.vault.vault_token_create:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    display_name: "{{ params.display_name }}"
    explicit_max_ttl: "{{ params.explicit_max_ttl }}"
    no_default_policy: "{{ params.no_default_policy }}"
    no_parent: "{{ params.no_parent }}"
    num_uses: "{{ params.num_uses }}"
    period: "{{ params.period }}"
    policies: "{{ params.policies }}"
    renewable: "{{ params.renewable }}"
  register: result

- name: Verify expected keys in response
  ansible.builtin.assert:
    that:
      - result is changed
      - result.data is defined
      - item in result.data
    fail_msg: "Missing key {{ item }} in result.data"
  loop: "{{ expected_response_keys }}"
  loop_control:
    label: "{{ item }}"
"""

RETURN = """
data:
  description: >-
    Extracted payload from the Vault C(auth) response envelope.
    Validated against the module argspec at runtime.
  returned: success
  type: dict
  contains:
    client_token:
      description: The generated client token value
      type: str
      returned: success
    accessor:
      description: The token accessor for management without the secret
      type: str
      returned: success
    policies:
      description: Policies attached to the token
      type: list
      returned: success
      elements: str
    token_policies:
      description: Policies directly assigned to the token
      type: list
      returned: success
      elements: str
    metadata:
      description: Metadata associated with the token
      type: dict
      returned: success
    lease_duration:
      description: Token TTL in seconds
      type: int
      returned: success
    renewable:
      description: Whether the token is renewable
      type: bool
      returned: success
    entity_id:
      description: Entity ID associated with the token
      type: str
      returned: success
    token_type:
      description: The type of token (service, batch)
      type: str
      returned: success
    orphan:
      description: Whether the token is an orphan
      type: bool
      returned: success
    num_uses:
      description: Number of uses remaining (0 means unlimited)
      type: int
      returned: success
raw:
  description: The full JSON response from Vault including the envelope.
  returned: success
  type: dict
"""
