# -*- coding: utf-8 -*-

# Copyright (c) 2025 Red Hat, Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# @generated
# This file is auto-generated by tools/generate_modules.py
# Do not edit manually -- re-run the generator instead.
# TODO: update from captured OpenAPI spec when database engine paths are available

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: vault_pki_issue
short_description: Issue a certificate from a PKI role
description:
  - Issue a certificate from a PKI role using the Vault HTTP API.
version_added: "2.0.0"
author:
  - HashiCorp Vault Collection Contributors
extends_documentation_fragment:
  - hashicorp.vault.vault_auth
options:
    role:
      description: Name of the PKI role to issue against
      type: str
      required: true
    mount_path:
      description: Mount path of the PKI secrets engine
      type: str
      default: pki
    alt_names:
      description:
        - The requested Subject Alternative Names, if any, in a comma-
        - delimited list. If email protection is enabled for the role,
        - this may contain email addresses.
      type: str
    cert_metadata:
      description:
        - User supplied metadata to store associated with this
        - certificate's serial number, base64 encoded
      type: str
    common_name:
      description:
        - The requested common name; if you want more than one,
        - specify the alternative names in the alt_names map. If email
        - protection is enabled in the role, this may be an email
        - address.
      type: str
    exclude_cn_from_sans:
      description:
        - If true, the Common Name will not be included in DNS or
        - Email Subject Alternate Names. Defaults to false (CN is
        - included).
      type: bool
      default: false
    format:
      description:
        - 'Format for returned data. Can be "pem", "der", or'
        - '"pem_bundle". If "pem_bundle", any private key and issuing'
        - 'cert will be appended to the certificate pem. If "der", the'
        - 'value will be base64 encoded. Defaults to "pem".'
      type: str
      default: pem
    ip_sans:
      description: The requested IP SANs, if any, in a comma-delimited list
      type: list
      elements: str
    issuer_ref:
      description:
        - 'Reference to a existing issuer; either "default" for the'
        - configured default issuer, an identifier or the name
        - assigned to the issuer.
      type: str
      default: default
    not_after:
      description:
        - Set the not after field of the certificate with specified
        - date value. The value format should be given in UTC format
        - YYYY-MM-ddTHH:MM:SSZ
      type: str
    other_sans:
      description:
        - Requested other SANs, in an array with the format
        - <oid>;UTF8:<utf8 string value> for each entry.
      type: list
      elements: str
    private_key_format:
      description:
        - Format for the returned private key. Generally the default
        - 'will be controlled by the "format" parameter as either'
        - base64-encoded DER or PEM-encoded DER. However, this can be
        - 'set to "pkcs8" to have the returned private key contain'
        - base64-encoded pkcs8 or PEM-encoded pkcs8 instead. Defaults
        - 'to "der".'
      type: str
      default: der
    remove_roots_from_chain:
      description:
        - Whether or not to remove self-signed CA certificates in the
        - output of the ca_chain field.
      type: bool
      default: false
    serial_number:
      description:
        - The Subject's requested serial number, if any. See RFC 4519
        - Section 2.31 'serialNumber' for a description of this field.
        - If you want more than one, specify alternative names in the
        - alt_names map using OID 2.5.4.5. This has no impact on the
        - final certificate's Serial Number field.
      type: str
    ttl:
      description:
        - The requested Time To Live for the certificate; sets the
        - expiration date. If not specified the role default, backend
        - default, or system default TTL is used, in that order.
        - Cannot be larger than the role max TTL.
      type: str
    uri_sans:
      description: The requested URI SANs, if any, in a comma-delimited list.
      type: list
      elements: str
    user_ids:
      description:
        - The requested user_ids value to place in the subject, if
        - any, in a comma-delimited list. Restricted by
        - allowed_user_ids. Any values are added with OID
        - 0.9.2342.19200300.100.1.1.
      type: list
      elements: str
"""

EXAMPLES = """
# vars_files: [vars.yml]
#
# params:
#   common_name: test.example.com
#   ttl: "1h"
#
# expected_response_keys:
#   - certificate
#   - serial_number
#   - private_key
#   - issuing_ca

- name: Issue a certificate from a PKI role
  hashicorp.vault.vault_pki_issue:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    mount_path: "{{ mount_path }}"
    role: "{{ role }}"
    common_name: "{{ params.common_name }}"
    ttl: "{{ params.ttl }}"
  register: result

- name: Verify expected keys in response
  ansible.builtin.assert:
    that:
      - result is changed
      - result.data is defined
      - item in result.data
    fail_msg: "Missing key {{ item }} in result.data"
  loop: "{{ expected_response_keys }}"
  loop_control:
    label: "{{ item }}"
"""

RETURN = """
data:
  description: >-
    Extracted payload from the Vault C(data) response envelope.
    Validated against the module argspec at runtime.
  returned: success
  type: dict
  contains:
    certificate:
      description: The PEM-encoded issued certificate
      type: str
      returned: success
    serial_number:
      description: The serial number of the certificate
      type: str
      returned: success
    private_key:
      description: The PEM-encoded private key
      type: str
      returned: success
    private_key_type:
      description: The type of private key (rsa, ec, ed25519)
      type: str
      returned: success
    issuing_ca:
      description: The PEM-encoded issuing CA certificate
      type: str
      returned: success
    ca_chain:
      description: The full CA chain including the issuing CA
      type: list
      returned: success
      elements: str
    expiration:
      description: Unix timestamp when the certificate expires
      type: int
      returned: success
raw:
  description: The full JSON response from Vault including the envelope.
  returned: success
  type: dict
"""
