# -*- coding: utf-8 -*-

# Copyright (c) 2025 Red Hat, Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# @generated
# This file is auto-generated by tools/generate_modules.py
# Do not edit manually -- re-run the generator instead.

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: vault_token_role
short_description: Manage Vault token roles
description:
  - Manage Vault token roles using the Vault HTTP API.
version_added: "2.0.0"
author:
  - HashiCorp Vault Collection Contributors
extends_documentation_fragment:
  - hashicorp.vault.vault_auth
options:
    state:
      description: Desired state of the resource.
      type: str
      choices: ['present', 'absent']
      default: present
    role_name:
      description: 'Path parameter: role_name'
      type: str
      required: true
    allowed_entity_aliases:
      description:
        - String or JSON list of allowed entity aliases. If set,
        - specifies the entity aliases which are allowed to be used
        - during token generation. This field supports globbing.
      type: list
      elements: str
    allowed_policies:
      description:
        - If set, tokens can be created with any subset of the
        - policies in this list, rather than the normal semantics of
        - tokens being a subset of the calling token's policies. The
        - parameter is a comma-delimited string of policy names.
      type: list
      elements: str
    allowed_policies_glob:
      description:
        - If set, tokens can be created with any subset of glob
        - matched policies in this list, rather than the normal
        - semantics of tokens being a subset of the calling token's
        - policies. The parameter is a comma-delimited string of
        - policy name globs.
      type: list
      elements: str
    disallowed_policies:
      description:
        - If set, successful token creation via this role will require
        - that no policies in the given list are requested. The
        - parameter is a comma-delimited string of policy names.
      type: list
      elements: str
    disallowed_policies_glob:
      description:
        - If set, successful token creation via this role will require
        - that no requested policies glob match any of policies in
        - this list. The parameter is a comma-delimited string of
        - policy name globs.
      type: list
      elements: str
    orphan:
      description:
        - If true, tokens created via this role will be orphan tokens
        - (have no parent)
      type: bool
    path_suffix:
      description:
        - If set, tokens created via this role will contain the given
        - suffix as a part of their path. This can be used to assist
        - use of the 'revoke-prefix' endpoint later on. The given
        - suffix must match the regular expression.\\w[\\w-.]+\\w
      type: str
    renewable:
      description:
        - Tokens created via this role will be renewable or not
        - 'according to this value. Defaults to "true".'
      type: bool
      default: true
    token_bound_cidrs:
      description:
        - Comma separated string or JSON list of CIDR blocks. If set,
        - specifies the blocks of IP addresses which are allowed to
        - use the generated token.
      type: list
      elements: str
    token_explicit_max_ttl:
      description:
        - If set, tokens created via this role carry an explicit
        - maximum TTL. During renewal, the current maximum TTL values
        - of the role and the mount are not checked for changes, and
        - any updates to these values will have no effect on the token
        - being renewed.
      type: str
    token_no_default_policy:
      description:
        - If true, the 'default' policy will not automatically be
        - added to generated tokens
      type: bool
    token_num_uses:
      description:
        - The maximum number of times a token may be used, a value of
        - zero means unlimited
      type: int
    token_period:
      description:
        - If set, tokens created via this role will have no max
        - lifetime; instead, their renewal period will be fixed to
        - this value. This takes an integer number of seconds, or a
        - 'string duration (e.g. "24h").'
      type: str
    token_type:
      description: The type of token to generate, service or batch
      type: str
      default: default-service
"""

EXAMPLES = """
# vars_files: [vars.yml]
#
# role_name: test-role
# config:
#   allowed_entity_aliases: ["entity-*"]
#   allowed_policies: ["default"]
#   orphan: true
#   renewable: true
#   token_type: default-service

- name: Manage Vault token roles (present)
  hashicorp.vault.vault_token_role:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    state: present
    role_name: "{{ role_name }}"
    allowed_entity_aliases: "{{ config.allowed_entity_aliases }}"
    allowed_policies: "{{ config.allowed_policies }}"
    orphan: "{{ config.orphan }}"
    renewable: "{{ config.renewable }}"
    token_type: "{{ config.token_type }}"
  register: result

- name: Verify return matches contract
  ansible.builtin.assert:
    that:
      - result is changed
      - (config | hashicorp.vault.vault_config_match(result.data)).match
    fail_msg: "Contract violation: {{ (config | hashicorp.vault.vault_config_match(result.data)).mismatches | to_json }}"

- name: Manage Vault token roles (absent)
  hashicorp.vault.vault_token_role:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    state: absent
    role_name: "{{ role_name }}"
  register: result

- name: Verify result
  ansible.builtin.assert:
    that:
      - result is not failed
"""

RETURN = """
data:
  description: >-
    Extracted payload from the Vault response envelope.
    Validated against the module argspec at runtime.
  returned: success
  type: dict
  contains:
    allowed_entity_aliases:
      description: String or JSON list of allowed entity aliases
      type: list
      returned: success
      elements: str
    allowed_policies:
      description: If set, tokens can be created with any subset of the policies in th...
      type: list
      returned: success
      elements: str
    allowed_policies_glob:
      description: If set, tokens can be created with any subset of glob matched polic...
      type: list
      returned: success
      elements: str
    disallowed_policies:
      description: If set, successful token creation via this role will require that n...
      type: list
      returned: success
      elements: str
    disallowed_policies_glob:
      description: If set, successful token creation via this role will require that n...
      type: list
      returned: success
      elements: str
    orphan:
      description: If true, tokens created via this role will be orphan tokens (have n...
      type: bool
      returned: success
    path_suffix:
      description: If set, tokens created via this role will contain the given suffix ...
      type: str
      returned: success
    renewable:
      description: Tokens created via this role will be renewable or not according to ...
      type: bool
      returned: success
    token_bound_cidrs:
      description: Comma separated string or JSON list of CIDR blocks
      type: list
      returned: success
      elements: str
    token_explicit_max_ttl:
      description: If set, tokens created via this role carry an explicit maximum TTL
      type: str
      returned: success
    token_no_default_policy:
      description: If true, the 'default' policy will not automatically be added to ge...
      type: bool
      returned: success
    token_num_uses:
      description: The maximum number of times a token may be used, a value of zero me...
      type: int
      returned: success
    token_period:
      description: If set, tokens created via this role will have no max lifetime; ins...
      type: str
      returned: success
    token_type:
      description: The type of token to generate, service or batch
      type: str
      returned: success
raw:
  description: The full JSON response from Vault including the envelope.
  returned: success
  type: dict
"""
