# -*- coding: utf-8 -*-

# Copyright (c) 2025 Red Hat, Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# @generated
# This file is auto-generated by tools/generate_modules.py
# Do not edit manually -- re-run the generator instead.

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: vault_token_renew
short_description: Renew a Vault token
description:
  - Renew a Vault token using the Vault HTTP API.
version_added: "2.0.0"
author:
  - Bradley Thornton (@cidrblock)
extends_documentation_fragment:
  - hashicorp.vault.vault_auth.modules
options:
    increment:
      description: The desired increment in seconds to the token expiration
      type: str
      default: "0"
    token:
      description: Token to renew (request body)
      type: str
"""

EXAMPLES = """
# vars_files: [vars.yml]
#
# params:
#   increment: "1h"
#
# expected_response_keys:
#   - client_token
#   - accessor
#   - policies
#   - renewable
#   - token_type
#   - lease_duration

- name: Renew a Vault token
  hashicorp.vault.vault_token_renew:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    increment: "{{ params.increment }}"
  register: result

- name: Verify expected keys in response
  ansible.builtin.assert:
    that:
      - result is changed
      - result.data is defined
      - item in result.data
    fail_msg: "Missing key {{ item }} in result.data"
  loop: "{{ expected_response_keys }}"
"""

RETURN = """
data:
  description: >-
    Extracted payload from the Vault C(auth) response envelope.
    Validated against the module argspec at runtime.
  returned: success
  type: dict
  contains:
    client_token:
      description: The renewed client token value
      type: str
      returned: success
    accessor:
      description: The token accessor
      type: str
      returned: success
    policies:
      description: Policies attached to the token
      type: list
      returned: success
      elements: str
    token_policies:
      description: Policies directly assigned to the token
      type: list
      returned: success
      elements: str
    metadata:
      description: Metadata associated with the token
      type: dict
      returned: success
    lease_duration:
      description: New TTL in seconds after renewal
      type: int
      returned: success
    renewable:
      description: Whether the token is still renewable
      type: bool
      returned: success
    entity_id:
      description: Entity ID associated with the token
      type: str
      returned: success
    token_type:
      description: The type of token (service, batch)
      type: str
      returned: success
raw:
  description: The full JSON response from Vault including the envelope.
  returned: success
  type: dict
"""
