# -*- coding: utf-8 -*-

# Copyright (c) 2025 Red Hat, Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# @generated
# This file is auto-generated by tools/generate_modules.py
# Do not edit manually -- re-run the generator instead.

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: vault_auth_method_info
short_description: List enabled Vault auth methods
description:
  - List enabled Vault auth methods using the Vault HTTP API.
version_added: "2.0.0"
author:
  - HashiCorp Vault Collection Contributors
extends_documentation_fragment:
  - hashicorp.vault.vault_auth.modules
options:

"""

EXAMPLES = """
# vars_files: [vars.yml]
#
# expected_auth_path: "token/"
#
# expected_entry_keys:
#   - type
#   - description
#   - accessor
#   - config
#   - local
#   - seal_wrap
#   - uuid

- name: List enabled Vault auth methods
  hashicorp.vault.vault_auth_method_info:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
  register: result

- name: Verify data contains expected auth path
  ansible.builtin.assert:
    that:
      - result is not changed
      - result.data is defined
      - expected_auth_path in result.data
    fail_msg: "Expected auth path '{{ expected_auth_path }}' not found in result.data"

- name: Verify auth method entry has expected keys
  ansible.builtin.assert:
    that:
      - item in result.data[expected_auth_path]
    fail_msg: "Missing key {{ item }} in result.data['{{ expected_auth_path }}']"
  loop: "{{ expected_entry_keys }}"
"""

RETURN = """
data:
  description: >-
    Dictionary mapping auth method mount paths (e.g. C(token/), C(userpass/)) to their configuration. Keys are dynamic mount paths.
  returned: success
  type: dict
  contains:
    type:
      description: Type of auth method (e.g. token, userpass, approle)
      type: str
      returned: success
    description:
      description: Description of the auth method
      type: str
      returned: success
    accessor:
      description: Unique accessor identifier for this auth method
      type: str
      returned: success
    config:
      description: Auth method configuration including TTL settings
      type: dict
      returned: success
    local:
      description: Whether the auth method is local only (not replicated)
      type: bool
      returned: success
    seal_wrap:
      description: Whether seal wrapping is enabled for this auth method
      type: bool
      returned: success
    uuid:
      description: UUID of the auth method mount
      type: str
      returned: success
    plugin_version:
      description: Configured plugin version (empty for builtin)
      type: str
      returned: success
    running_plugin_version:
      description: Currently running plugin version
      type: str
      returned: success
    options:
      description: Auth method mount options
      type: dict
      returned: success
raw:
  description: The full JSON response from Vault including the envelope.
  returned: success
  type: dict
"""
