# -*- coding: utf-8 -*-

# Copyright (c) 2025 Red Hat, Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# @generated
# This file is auto-generated by tools/generate_modules.py
# Do not edit manually -- re-run the generator instead.

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: vault_token_list_accessors
short_description: List all token accessors
description:
  - List all token accessors using the Vault HTTP API.
version_added: "2.0.0"
author:
  - HashiCorp Vault Collection Contributors
extends_documentation_fragment:
  - hashicorp.vault.vault_auth.modules
options:

"""

EXAMPLES = """
# vars_files: [vars.yml]
#
# expected_response_keys:
#   - keys

- name: List all token accessors
  hashicorp.vault.vault_token_list_accessors:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
  register: result

- name: Verify expected keys in response
  ansible.builtin.assert:
    that:
      - result is not changed
      - result.data is defined
      - item in result.data
    fail_msg: "Missing key {{ item }} in result.data"
  loop: "{{ expected_response_keys }}"

- name: Verify keys is a list
  ansible.builtin.assert:
    that:
      - result.data['keys'] | type_debug == 'list'
    fail_msg: "result.data['keys'] should be a list, got {{ result.data['keys'] | type_debug }}"
"""

RETURN = """
data:
  description: >-
    Extracted payload from the Vault C(data) response envelope.
    Validated against the module argspec at runtime.
  returned: success
  type: dict
  contains:
    keys:
      description: List of token accessors
      type: list
      returned: success
      elements: str
raw:
  description: The full JSON response from Vault including the envelope.
  returned: success
  type: dict
"""
