# -*- coding: utf-8 -*-

# Copyright (c) 2025 Red Hat, Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# @generated
# This file is auto-generated by tools/generate_modules.py
# Do not edit manually -- re-run the generator instead.
# TODO: update from captured OpenAPI spec when database engine paths are available

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: vault_database_rotate_root
short_description: Rotate the root credentials for a database connection
description:
  - Rotate the root credentials for a database connection using the Vault HTTP API.
version_added: "2.0.0"
author:
  - HashiCorp Vault Collection Contributors
extends_documentation_fragment:
  - hashicorp.vault.vault_auth
options:
    name:
      description: Name of the database connection
      type: str
      required: true
    mount_path:
      description: Mount path of the database secrets engine
      type: str
      default: database
"""

EXAMPLES = """
# vars_files: [vars.yml]
#
# mount_path: database
# name: rotate-test-conn
#
# Rotate is fire-and-forget; Vault returns no meaningful data.

- name: Rotate the root credentials for a database connection
  hashicorp.vault.vault_database_rotate_root:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    mount_path: "{{ mount_path }}"
    name: "{{ name }}"
  register: result

- name: Verify result
  ansible.builtin.assert:
    that:
      - result is changed
"""

RETURN = """
data:
  description: >-
    Extracted payload from the Vault response envelope. Contains the
    resource fields from the C(data) or C(auth) key of the API response.
    Validated against the module argspec at runtime.
  returned: success
  type: dict
raw:
  description: The full JSON response from Vault including the envelope.
  returned: success
  type: dict
"""
