# -*- coding: utf-8 -*-

# Copyright (c) 2025 Red Hat, Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# @generated
# This file is auto-generated by tools/generate_modules.py
# Do not edit manually -- re-run the generator instead.
# TODO: update from captured OpenAPI spec when database engine paths are available

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: vault_database_static_role
short_description: Manage Vault database static roles
description:
  - Manage Vault database static roles using the Vault HTTP API.
version_added: "2.0.0"
author:
  - Bradley Thornton (@cidrblock)
extends_documentation_fragment:
  - hashicorp.vault.vault_auth.modules
options:
    state:
      description: Desired state of the resource.
      type: str
      choices: ['present', 'absent']
      default: present
    name:
      description: Name of the static role
      type: str
      required: true
    mount_path:
      description: Mount path of the database secrets engine
      type: str
      default: database
    credential_config:
      description: Configuration for the credential type
      type: dict
    credential_type:
      description: Type of credential to manage (e.g. 'password')
      type: str
    db_name:
      description: Name of the database connection to use
      type: str
    rotation_period:
      description:
        - Period for automatic credential rotation (e.g. '24h').
        - Mutually exclusive with rotation_schedule.
      type: str
    rotation_schedule:
      description:
        - Cron-style schedule for credential rotation. Mutually
        - exclusive with rotation_period.
      type: str
    rotation_statements:
      description: SQL statements to rotate the password
      type: list
      elements: str
    rotation_window:
      description: Window in seconds for scheduled rotation
      type: int
    username:
      description: Database username that this role corresponds to
      type: str
"""

EXAMPLES = """
# vars_files: [vars.yml]
#
# name: test-static-role
# mount_path: database
# config:
#   db_name: my-postgres
#   username: vault-user
#   credential_type: password
#   rotation_period: "24h"

- name: Manage Vault database static roles (present)
  hashicorp.vault.vault_database_static_role:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    state: present
    mount_path: "{{ mount_path }}"
    name: "{{ name }}"
    db_name: "{{ config.db_name }}"
    username: "{{ config.username }}"
    credential_type: "{{ config.credential_type }}"
    rotation_period: "{{ config.rotation_period }}"
  register: result

- name: Verify return matches contract
  ansible.builtin.assert:
    that:
      - result is changed
      - (config | hashicorp.vault.vault_config_match(result.data)).match
    fail_msg: "Contract violation: {{ (config | hashicorp.vault.vault_config_match(result.data)).mismatches | to_json }}"

- name: Manage Vault database static roles (absent)
  hashicorp.vault.vault_database_static_role:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    state: absent
    mount_path: "{{ mount_path }}"
    name: "{{ name }}"
  register: result

- name: Verify result
  ansible.builtin.assert:
    that:
      - result is not failed
"""

RETURN = """
data:
  description: >-
    Extracted payload from the Vault response envelope.
    Validated against the module argspec at runtime.
  returned: success
  type: dict
  contains:
    credential_config:
      description: Configuration for the credential type
      type: dict
      returned: success
    credential_type:
      description: Type of credential to manage (e
      type: str
      returned: success
    db_name:
      description: Name of the database connection to use
      type: str
      returned: success
    rotation_period:
      description: Period for automatic credential rotation (e
      type: str
      returned: success
    rotation_schedule:
      description: Cron-style schedule for credential rotation
      type: str
      returned: success
    rotation_statements:
      description: SQL statements to rotate the password
      type: list
      returned: success
      elements: str
    rotation_window:
      description: Window in seconds for scheduled rotation
      type: int
      returned: success
    username:
      description: Database username that this role corresponds to
      type: str
      returned: success
raw:
  description: The full JSON response from Vault including the envelope.
  returned: success
  type: dict
"""
