# -*- coding: utf-8 -*-

# Copyright (c) 2025 Red Hat, Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# @generated
# This file is auto-generated by tools/generate_modules.py
# Do not edit manually -- re-run the generator instead.
# TODO: update from captured OpenAPI spec when database engine paths are available

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: vault_pki_role
short_description: Manage Vault PKI roles
description:
  - Manage Vault PKI roles using the Vault HTTP API.
version_added: "2.0.0"
author:
  - HashiCorp Vault Collection Contributors
extends_documentation_fragment:
  - hashicorp.vault.vault_auth
options:
    state:
      description: Desired state of the resource.
      type: str
      choices: ['present', 'absent']
      default: present
    name:
      description: Name of the PKI role
      type: str
      required: true
    mount_path:
      description: Mount path of the PKI secrets engine
      type: str
      default: pki
    allow_any_name:
      description:
        - If set, clients can request certificates for any domain,
        - regardless of allowed_domains restrictions. See the
        - documentation for more information.
      type: bool
    allow_bare_domains:
      description:
        - If set, clients can request certificates for the base
        - 'domains themselves, e.g. "example.com" of domains listed in'
        - allowed_domains. This is a separate option as in some cases
        - this can be considered a security threat. See the
        - documentation for more information.
      type: bool
    allow_glob_domains:
      description:
        - If set, domains specified in allowed_domains can include
        - 'shell-style glob patterns, e.g. "ftp*.example.com". See the'
        - documentation for more information.
      type: bool
    allow_ip_sans:
      description:
        - If set, IP Subject Alternative Names are allowed. Any valid
        - IP is accepted and No authorization checking is performed.
      type: bool
      default: true
    allow_localhost:
      description:
        - 'Whether to allow "localhost" and "localdomain" as a valid'
        - common name in a request, independent of allowed_domains
        - value.
      type: bool
      default: true
    allow_subdomains:
      description:
        - If set, clients can request certificates for subdomains of
        - domains listed in allowed_domains, including wildcard
        - subdomains. See the documentation for more information.
      type: bool
    allow_wildcard_certificates:
      description:
        - If set, allows certificates with wildcards in the common
        - name to be issued, conforming to RFC 6125's Section 6.4.3;
        - 'e.g., "*.example.net" or "b*z.example.net". See the'
        - documentation for more information.
      type: bool
      default: true
    allowed_domains:
      description:
        - Specifies the domains this role is allowed to issue
        - certificates for. This is used with the allow_bare_domains,
        - allow_subdomains, and allow_glob_domains to determine
        - matches for the common name, DNS-typed SAN entries, and
        - Email-typed SAN entries of certificates. See the
        - documentation for more information. This parameter accepts a
        - comma-separated string or list of domains.
      type: list
      elements: str
    allowed_domains_template:
      description:
        - If set, Allowed domains can be specified using identity
        - template policies. Non-templated domains are also permitted.
      type: bool
      default: false
    allowed_other_sans:
      description:
        - If set, an array of allowed other names to put in SANs.
        - These values support globbing and must be in the format
        - '<oid>;<type>:<value>. Currently only "utf8" is a valid type.'
        - All values, including globbing values, must use this syntax,
        - 'with the exception being a single "*" which allows any OID'
        - and any value (but type must still be utf8).
      type: list
      elements: str
    allowed_serial_numbers:
      description:
        - If set, an array of allowed serial numbers to put in
        - Subject. These values support globbing.
      type: list
      elements: str
    allowed_uri_sans:
      description:
        - If set, an array of allowed URIs for URI Subject Alternative
        - Names. Any valid URI is accepted, these values support
        - globbing.
      type: list
      elements: str
    allowed_uri_sans_template:
      description:
        - If set, Allowed URI SANs can be specified using identity
        - template policies. Non-templated URI SANs are also
        - permitted.
      type: bool
      default: false
    allowed_user_ids:
      description:
        - If set, an array of allowed user-ids to put in user system
        - 'login name specified here: https://www.rfc-'
        - editor.org/rfc/rfc1274#section-9.3.1
      type: list
      elements: str
    backend:
      description: Backend Type
      type: str
    basic_constraints_valid_for_non_ca:
      description:
        - Mark Basic Constraints valid when issuing non-CA
        - certificates.
      type: bool
    client_flag:
      description:
        - If set, certificates are flagged for client auth use.
        - Defaults to true. See also RFC 5280 Section 4.2.1.12.
      type: bool
      default: true
    cn_validations:
      description:
        - List of allowed validations to run against the Common Name
        - field. Values can include 'email' to validate the CN is a
        - email address, 'hostname' to validate the CN is a valid
        - hostname (potentially including wildcards). When multiple
        - validations are specified, these take OR semantics (either
        - email OR hostname are allowed). The special value 'disabled'
        - allows disabling all CN name validations, allowing for
        - arbitrary non-Hostname, non-Email address CNs.
      type: list
      elements: str
      default: ['email', 'hostname']
    code_signing_flag:
      description:
        - If set, certificates are flagged for code signing use.
        - Defaults to false. See also RFC 5280 Section 4.2.1.12.
      type: bool
    country:
      description:
        - If set, Country will be set to this value in certificates
        - issued by this role.
      type: list
      elements: str
    email_protection_flag:
      description:
        - If set, certificates are flagged for email protection use.
        - Defaults to false. See also RFC 5280 Section 4.2.1.12.
      type: bool
    enforce_hostnames:
      description:
        - If set, only valid host names are allowed for CN and DNS
        - SANs, and the host part of email addresses. Defaults to
        - true.
      type: bool
      default: true
    ext_key_usage:
      description:
        - A comma-separated string or list of extended key usages.
        - Valid values can be found at
        - https://golang.org/pkg/crypto/x509/#ExtKeyUsage -- simply
        - 'drop the "ExtKeyUsage" part of the name. To remove all key'
        - usages from being set, set this value to an empty list. See
        - also RFC 5280 Section 4.2.1.12.
      type: list
      elements: str
      default: []
    ext_key_usage_oids:
      description: A comma-separated string or list of extended key usage oids.
      type: list
      elements: str
    generate_lease:
      description:
        - If set, certificates issued/signed against this role will
        - 'have Vault leases attached to them. Defaults to "false".'
        - 'Certificates can be added to the CRL by "vault revoke'
        - '<lease_id>" when certificates are associated with leases. It'
        - 'can also be done using the "pki/revoke" endpoint. However,'
        - 'when lease generation is disabled, invoking "pki/revoke"'
        - would be the only way to add the certificates to the CRL.
        - When large number of certificates are generated with long
        - lifetimes, it is recommended that lease generation be
        - disabled, as large amount of leases adversely affect the
        - startup time of Vault.
      type: bool
    issuer_ref:
      description:
        - Reference to the issuer used to sign requests serviced by
        - this role.
      type: str
      default: default
    key_bits:
      description:
        - The number of bits to use. Allowed values are 0 (universal
        - 'default); with rsa key_type: 2048 (default), 3072, or 4096;'
        - 'with ec key_type: 224, 256 (default), 384, or 521; ignored'
        - with ed25519.
      type: int
      default: 0
    key_type:
      description:
        - 'The type of key to use; defaults to RSA. "rsa" "ec",'
        - '"ed25519" and "any" are the only valid values.'
      type: str
      default: rsa
    key_usage:
      description:
        - A comma-separated string or list of key usages (not extended
        - key usages). Valid values can be found at
        - https://golang.org/pkg/crypto/x509/#KeyUsage -- simply drop
        - 'the "KeyUsage" part of the name. To remove all key usages'
        - from being set, set this value to an empty list. See also
        - RFC 5280 Section 4.2.1.3.
      type: list
      elements: str
      default: ['DigitalSignature', 'KeyAgreement', 'KeyEncipherment']
    locality:
      description:
        - If set, Locality will be set to this value in certificates
        - issued by this role.
      type: list
      elements: str
    max_ttl:
      description:
        - The maximum allowed lease duration. If not set, defaults to
        - the system maximum lease TTL.
      type: str
    no_store:
      description:
        - If set, certificates issued/signed against this role will
        - not be stored in the storage backend. This can improve
        - performance when issuing large numbers of certificates.
        - However, certificates issued in this way cannot be
        - enumerated or revoked, so this option is recommended only
        - for certificates that are non-sensitive, or extremely short-
        - 'lived. This option implies a value of "false" for'
        - '"generate_lease".'
      type: bool
    not_after:
      description:
        - Set the not after field of the certificate with specified
        - date value. The value format should be given in UTC format
        - YYYY-MM-ddTHH:MM:SSZ.
      type: str
    not_before_duration:
      description:
        - The duration before now which the certificate needs to be
        - backdated by.
      type: str
      default: 30
    organization:
      description:
        - If set, O (Organization) will be set to this value in
        - certificates issued by this role.
      type: list
      elements: str
    ou:
      description:
        - If set, OU (OrganizationalUnit) will be set to this value in
        - certificates issued by this role.
      type: list
      elements: str
    policy_identifiers:
      description:
        - A comma-separated string or list of policy OIDs, or a JSON
        - list of qualified policy information, which must include an
        - oid, and may include a notice and/or cps url, using the form
        - '[{"oid"="1.3.6.1.4.1.7.8","notice"="I am a user Notice"}, {"'
        - 'oid"="1.3.6.1.4.1.32473.1.2.4","cps"="https://example.com"}]'
        - .
      type: list
      elements: str
    postal_code:
      description:
        - If set, Postal Code will be set to this value in
        - certificates issued by this role.
      type: list
      elements: str
    province:
      description:
        - If set, Province will be set to this value in certificates
        - issued by this role.
      type: list
      elements: str
    require_cn:
      description:
        - If set to false, makes the 'common_name' field optional
        - while generating a certificate.
      type: bool
      default: true
    serial_number_source:
      description:
        - 'Source for the certificate subject serial number. If "json-'
        - 'csr" (default), the value from the JSON serial_number field'
        - is used, falling back to the value in the CSR if empty. If
        - '"json", the value from the serial_number JSON field is used,'
        - ignoring the value in the CSR.
      type: str
      default: json-csr
    server_flag:
      description:
        - If set, certificates are flagged for server auth use.
        - Defaults to true. See also RFC 5280 Section 4.2.1.12.
      type: bool
      default: true
    signature_bits:
      description:
        - The number of bits to use in the signature algorithm;
        - accepts 256 for SHA-2-256, 384 for SHA-2-384, and 512 for
        - SHA-2-512. Defaults to 0 to automatically detect based on
        - key length (SHA-2-256 for RSA keys, and matching the curve
        - size for NIST P-Curves).
      type: int
      default: 0
    street_address:
      description:
        - If set, Street Address will be set to this value in
        - certificates issued by this role.
      type: list
      elements: str
    ttl:
      description:
        - The lease duration (validity period of the certificate) if
        - no specific lease duration is requested. The lease duration
        - controls the expiration of certificates issued by this
        - backend. Defaults to the system default value or the value
        - of max_ttl, whichever is shorter.
      type: str
    use_csr_common_name:
      description:
        - If set, when used with a signing profile, the common name in
        - the CSR will be used. This does *not* include any requested
        - Subject Alternative Names; use use_csr_sans for that.
        - Defaults to true.
      type: bool
      default: true
    use_csr_sans:
      description:
        - If set, when used with a signing profile, the SANs in the
        - CSR will be used. This does *not* include the Common Name
        - (cn); use use_csr_common_name for that. Defaults to true.
      type: bool
      default: true
    use_pss:
      description:
        - Whether or not to use PSS signatures when using a RSA key-
        - type issuer. Defaults to false.
      type: bool
      default: false
"""

EXAMPLES = """
# vars_files: [vars.yml]
#
# name: test-pki-role
# mount_path: pki
# config:
#   allowed_domains: ["example.com"]
#   allow_subdomains: true
#   max_ttl: "72h"

- name: Manage Vault PKI roles (present)
  hashicorp.vault.vault_pki_role:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    state: present
    mount_path: "{{ mount_path }}"
    name: "{{ name }}"
    allowed_domains: "{{ config.allowed_domains }}"
    allow_subdomains: "{{ config.allow_subdomains }}"
    max_ttl: "{{ config.max_ttl }}"
  register: result

- name: Verify return matches contract
  ansible.builtin.assert:
    that:
      - result is changed
      - (config | hashicorp.vault.vault_config_match(result.data)).match
    fail_msg: "Contract violation: {{ (config | hashicorp.vault.vault_config_match(result.data)).mismatches | to_json }}"

- name: Manage Vault PKI roles (absent)
  hashicorp.vault.vault_pki_role:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    state: absent
    mount_path: "{{ mount_path }}"
    name: "{{ name }}"
  register: result

- name: Verify result
  ansible.builtin.assert:
    that:
      - result is not failed
"""

RETURN = """
data:
  description: >-
    Extracted payload from the Vault response envelope.
    Validated against the module argspec at runtime.
  returned: success
  type: dict
  contains:
    allow_any_name:
      description: If set, clients can request certificates for any domain, regardless...
      type: bool
      returned: success
    allow_bare_domains:
      description: If set, clients can request certificates for the base domains thems...
      type: bool
      returned: success
    allow_glob_domains:
      description: If set, domains specified in allowed_domains can include shell-styl...
      type: bool
      returned: success
    allow_ip_sans:
      description: If set, IP Subject Alternative Names are allowed
      type: bool
      returned: success
    allow_localhost:
      description: 'Whether to allow "localhost" and "localdomain" as a valid common na...'
      type: bool
      returned: success
    allow_subdomains:
      description: If set, clients can request certificates for subdomains of domains ...
      type: bool
      returned: success
    allow_wildcard_certificates:
      description: If set, allows certificates with wildcards in the common name to be...
      type: bool
      returned: success
    allowed_domains:
      description: Specifies the domains this role is allowed to issue certificates for
      type: list
      returned: success
      elements: str
    allowed_domains_template:
      description: If set, Allowed domains can be specified using identity template po...
      type: bool
      returned: success
    allowed_other_sans:
      description: If set, an array of allowed other names to put in SANs
      type: list
      returned: success
      elements: str
    allowed_serial_numbers:
      description: If set, an array of allowed serial numbers to put in Subject
      type: list
      returned: success
      elements: str
    allowed_uri_sans:
      description: If set, an array of allowed URIs for URI Subject Alternative Names
      type: list
      returned: success
      elements: str
    allowed_uri_sans_template:
      description: If set, Allowed URI SANs can be specified using identity template p...
      type: bool
      returned: success
    allowed_user_ids:
      description: If set, an array of allowed user-ids to put in user system login na...
      type: list
      returned: success
      elements: str
    backend:
      description: Backend Type
      type: str
      returned: success
    basic_constraints_valid_for_non_ca:
      description: Mark Basic Constraints valid when issuing non-CA certificates
      type: bool
      returned: success
    client_flag:
      description: If set, certificates are flagged for client auth use
      type: bool
      returned: success
    cn_validations:
      description: List of allowed validations to run against the Common Name field
      type: list
      returned: success
      elements: str
    code_signing_flag:
      description: If set, certificates are flagged for code signing use
      type: bool
      returned: success
    country:
      description: If set, Country will be set to this value in certificates issued by...
      type: list
      returned: success
      elements: str
    email_protection_flag:
      description: If set, certificates are flagged for email protection use
      type: bool
      returned: success
    enforce_hostnames:
      description: If set, only valid host names are allowed for CN and DNS SANs, and ...
      type: bool
      returned: success
    ext_key_usage:
      description: A comma-separated string or list of extended key usages
      type: list
      returned: success
      elements: str
    ext_key_usage_oids:
      description: A comma-separated string or list of extended key usage oids
      type: list
      returned: success
      elements: str
    generate_lease:
      description: If set, certificates issued/signed against this role will have Vaul...
      type: bool
      returned: success
    issuer_ref:
      description: Reference to the issuer used to sign requests serviced by this role
      type: str
      returned: success
    key_bits:
      description: The number of bits to use
      type: int
      returned: success
    key_type:
      description: The type of key to use; defaults to RSA
      type: str
      returned: success
    key_usage:
      description: A comma-separated string or list of key usages (not extended key us...
      type: list
      returned: success
      elements: str
    locality:
      description: If set, Locality will be set to this value in certificates issued b...
      type: list
      returned: success
      elements: str
    max_ttl:
      description: The maximum allowed lease duration
      type: str
      returned: success
    no_store:
      description: If set, certificates issued/signed against this role will not be st...
      type: bool
      returned: success
    not_after:
      description: Set the not after field of the certificate with specified date value
      type: str
      returned: success
    not_before_duration:
      description: The duration before now which the certificate needs to be backdated by
      type: str
      returned: success
    organization:
      description: If set, O (Organization) will be set to this value in certificates ...
      type: list
      returned: success
      elements: str
    ou:
      description: If set, OU (OrganizationalUnit) will be set to this value in certif...
      type: list
      returned: success
      elements: str
    policy_identifiers:
      description: A comma-separated string or list of policy OIDs, or a JSON list of ...
      type: list
      returned: success
      elements: str
    postal_code:
      description: If set, Postal Code will be set to this value in certificates issue...
      type: list
      returned: success
      elements: str
    province:
      description: If set, Province will be set to this value in certificates issued b...
      type: list
      returned: success
      elements: str
    require_cn:
      description: If set to false, makes the 'common_name' field optional while gener...
      type: bool
      returned: success
    serial_number_source:
      description: Source for the certificate subject serial number
      type: str
      returned: success
    server_flag:
      description: If set, certificates are flagged for server auth use
      type: bool
      returned: success
    signature_bits:
      description: The number of bits to use in the signature algorithm; accepts 256 f...
      type: int
      returned: success
    street_address:
      description: If set, Street Address will be set to this value in certificates is...
      type: list
      returned: success
      elements: str
    ttl:
      description: The lease duration (validity period of the certificate) if no speci...
      type: str
      returned: success
    use_csr_common_name:
      description: If set, when used with a signing profile, the common name in the CS...
      type: bool
      returned: success
    use_csr_sans:
      description: If set, when used with a signing profile, the SANs in the CSR will ...
      type: bool
      returned: success
    use_pss:
      description: Whether or not to use PSS signatures when using a RSA key-type issuer
      type: bool
      returned: success
raw:
  description: The full JSON response from Vault including the envelope.
  returned: success
  type: dict
"""
