# -*- coding: utf-8 -*-

# Copyright (c) 2025 Red Hat, Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# @generated
# This file is auto-generated by tools/generate_modules.py
# Do not edit manually -- re-run the generator instead.
# TODO: update from captured OpenAPI spec when database engine paths are available

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: vault_database_role
short_description: Manage Vault database dynamic roles
description:
  - Manage Vault database dynamic roles using the Vault HTTP API.
version_added: "2.0.0"
author:
  - HashiCorp Vault Collection Contributors
extends_documentation_fragment:
  - hashicorp.vault.vault_auth.modules
options:
    state:
      description: Desired state of the resource.
      type: str
      choices: ['present', 'absent']
      default: present
    name:
      description: Name of the dynamic role
      type: str
      required: true
    mount_path:
      description: Mount path of the database secrets engine
      type: str
      default: database
    creation_statements:
      description: Database statements to create and configure a user
      type: list
      elements: str
    credential_config:
      description: Configuration for the credential type
      type: dict
    credential_type:
      description: Type of credential to manage
      type: str
      default: password
    db_name:
      description: Name of the database connection to use
      type: str
    default_ttl:
      description: Default TTL for generated credentials
      type: str
    max_ttl:
      description: Maximum TTL for generated credentials
      type: str
    renew_statements:
      description: Database statements to renew a user
      type: list
      elements: str
    revocation_statements:
      description: Database statements to revoke a user
      type: list
      elements: str
    rollback_statements:
      description: Database statements to rollback a create operation
      type: list
      elements: str
"""

EXAMPLES = """
# vars_files: [vars.yml]
#
# name: test-dynamic-role
# mount_path: database
# config:
#   db_name: my-postgres
#   creation_statements: ["CREATE ROLE ..."]
#   default_ttl: "1h"
#   max_ttl: "24h"

- name: Manage Vault database dynamic roles (present)
  hashicorp.vault.vault_database_role:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    state: present
    mount_path: "{{ mount_path }}"
    name: "{{ name }}"
    db_name: "{{ config.db_name }}"
    creation_statements: "{{ config.creation_statements }}"
    default_ttl: "{{ config.default_ttl }}"
    max_ttl: "{{ config.max_ttl }}"
  register: result

- name: Verify return matches contract
  ansible.builtin.assert:
    that:
      - result is changed
      - (config | hashicorp.vault.vault_config_match(result.data)).match
    fail_msg: "Contract violation: {{ (config | hashicorp.vault.vault_config_match(result.data)).mismatches | to_json }}"

- name: Manage Vault database dynamic roles (absent)
  hashicorp.vault.vault_database_role:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    state: absent
    mount_path: "{{ mount_path }}"
    name: "{{ name }}"
  register: result

- name: Verify result
  ansible.builtin.assert:
    that:
      - result is not failed
"""

RETURN = """
data:
  description: >-
    Extracted payload from the Vault response envelope.
    Validated against the module argspec at runtime.
  returned: success
  type: dict
  contains:
    creation_statements:
      description: Database statements to create and configure a user
      type: list
      returned: success
      elements: str
    credential_config:
      description: Configuration for the credential type
      type: dict
      returned: success
    credential_type:
      description: Type of credential to manage
      type: str
      returned: success
    db_name:
      description: Name of the database connection to use
      type: str
      returned: success
    default_ttl:
      description: Default TTL for generated credentials
      type: str
      returned: success
    max_ttl:
      description: Maximum TTL for generated credentials
      type: str
      returned: success
    renew_statements:
      description: Database statements to renew a user
      type: list
      returned: success
      elements: str
    revocation_statements:
      description: Database statements to revoke a user
      type: list
      returned: success
      elements: str
    rollback_statements:
      description: Database statements to rollback a create operation
      type: list
      returned: success
      elements: str
raw:
  description: The full JSON response from Vault including the envelope.
  returned: success
  type: dict
"""
