# -*- coding: utf-8 -*-

# Copyright (c) 2025 Red Hat, Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# @generated
# This file is auto-generated by tools/generate_modules.py
# Do not edit manually -- re-run the generator instead.

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: vault_auth_method
short_description: Manage Vault auth methods
description:
  - Manage Vault auth methods using the Vault HTTP API.
version_added: "2.0.0"
author:
  - HashiCorp Vault Collection Contributors
extends_documentation_fragment:
  - hashicorp.vault.vault_auth.modules
options:
    state:
      description: Desired state of the resource.
      type: str
      choices: ['present', 'absent']
      default: present
    path:
      description: 'Path parameter: path'
      type: str
      required: true
    config:
      description: Configuration for this mount, such as plugin_name.
      type: dict
    description:
      description: User-friendly description for this credential backend.
      type: str
    external_entropy_access:
      description:
        - Whether to give the mount access to Vault's external
        - entropy.
      type: bool
      default: false
    local:
      description:
        - Mark the mount as a local mount, which is not replicated and
        - is unaffected by replication.
      type: bool
      default: false
    options:
      description:
        - The options to pass into the backend. Should be a json
        - object with string keys and values.
      type: dict
    plugin_name:
      description:
        - Name of the auth plugin to use based from the name in the
        - plugin catalog.
      type: str
    plugin_version:
      description:
        - The semantic version of the plugin to use, or image tag if
        - oci_image is provided.
      type: str
    seal_wrap:
      description: Whether to turn on seal wrapping for the mount.
      type: bool
      default: false
    type:
      description: 'The type of the backend. Example: "userpass"'
      type: str
"""

EXAMPLES = """
# vars_files: [vars.yml]
#
# auth_path: userpass
# config:
#   type: userpass
#   description: "Managed by Ansible"

- name: Manage Vault auth methods (present)
  hashicorp.vault.vault_auth_method:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    state: present
    path: "{{ auth_path }}"
    type: "{{ config.type }}"
    description: "{{ config.description }}"
  register: result

- name: Verify return matches contract
  ansible.builtin.assert:
    that:
      - result is changed
      - (config | hashicorp.vault.vault_config_match(result.data)).match
    fail_msg: >-
      Contract violation:
      {{ (config | hashicorp.vault.vault_config_match(result.data)).mismatches | to_json }}

- name: Manage Vault auth methods (absent)
  hashicorp.vault.vault_auth_method:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    state: absent
    path: "{{ auth_path }}"
  register: result

- name: Verify result
  ansible.builtin.assert:
    that:
      - result is not failed
"""

RETURN = """
data:
  description: >-
    Extracted payload from the Vault response envelope.
    Validated against the module argspec at runtime.
  returned: success
  type: dict
  contains:
    config:
      description: Configuration for this mount, such as plugin_name
      type: dict
      returned: success
    description:
      description: User-friendly description for this credential backend
      type: str
      returned: success
    external_entropy_access:
      description: Whether to give the mount access to Vault's external entropy
      type: bool
      returned: success
    local:
      description: Mark the mount as a local mount, which is not replicated and is una...
      type: bool
      returned: success
    options:
      description: The options to pass into the backend
      type: dict
      returned: success
    plugin_name:
      description: Name of the auth plugin to use based from the name in the plugin ca...
      type: str
      returned: success
    plugin_version:
      description: The semantic version of the plugin to use, or image tag if oci_imag...
      type: str
      returned: success
    seal_wrap:
      description: Whether to turn on seal wrapping for the mount
      type: bool
      returned: success
    type:
      description: The type of the backend
      type: str
      returned: success
raw:
  description: The full JSON response from Vault including the envelope.
  returned: success
  type: dict
"""
