# -*- coding: utf-8 -*-

# Copyright (c) 2025 Red Hat, Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# @generated
# This file is auto-generated by tools/generate_modules.py
# Do not edit manually -- re-run the generator instead.

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: vault_token_role_info
short_description: Read or list Vault token roles
description:
  - Read or list Vault token roles using the Vault HTTP API.
version_added: "2.0.0"
author:
  - HashiCorp Vault Collection Contributors
extends_documentation_fragment:
  - hashicorp.vault.vault_auth.modules
options:
    role_name:
      description: 'Path parameter: role_name'
      type: str
      required: true
"""

EXAMPLES = """
# vars_files: [vars.yml]
#
# role_name: test-role
# config:
#   allowed_policies: ["default"]
#   orphan: true
#   renewable: true
#   token_type: default-service

- name: Read or list Vault token roles
  hashicorp.vault.vault_token_role_info:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    role_name: "{{ role_name }}"
  register: result

- name: Verify return matches contract
  ansible.builtin.assert:
    that:
      - result is not changed
      - (config | hashicorp.vault.vault_config_match(result.data)).match
    fail_msg: "Contract violation: {{ (config | hashicorp.vault.vault_config_match(result.data)).mismatches | to_json }}"
"""

RETURN = """
data:
  description: >-
    Extracted payload from the Vault response envelope. Contains the
    resource fields from the C(data) or C(auth) key of the API response.
    Validated against the module argspec at runtime.
  returned: success
  type: dict
raw:
  description: The full JSON response from Vault including the envelope.
  returned: success
  type: dict
"""
