# -*- coding: utf-8 -*-

# Copyright (c) 2025 Red Hat, Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# @generated
# This file is auto-generated by tools/generate_modules.py
# Do not edit manually -- re-run the generator instead.

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: vault_token_lookup
short_description: Look up information about a Vault token
description:
  - Look up information about a Vault token using the Vault HTTP API.
version_added: "2.0.0"
author:
  - Bradley Thornton (@cidrblock)
extends_documentation_fragment:
  - hashicorp.vault.vault_auth.modules
options:
    token:
      description: Token to lookup
      type: str
"""

EXAMPLES = """
# vars_files: [vars.yml]
#
# expected_response_keys:
#   - accessor
#   - creation_time
#   - display_name
#   - id
#   - policies
#   - renewable

- name: Look up information about a Vault token
  hashicorp.vault.vault_token_lookup:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
  register: result

- name: Verify expected keys in response
  ansible.builtin.assert:
    that:
      - result.data is defined
      - item in result.data
    fail_msg: "Missing key {{ item }} in result.data"
  loop: "{{ expected_response_keys }}"
  loop_control:
    label: "{{ item }}"
"""

RETURN = """
data:
  description: >-
    Extracted payload from the Vault C(data) response envelope.
    Validated against the module argspec at runtime.
  returned: success
  type: dict
  contains:
    accessor:
      description: The token accessor
      type: str
      returned: success
    creation_time:
      description: Unix timestamp when the token was created
      type: int
      returned: success
    creation_ttl:
      description: Original TTL at creation in seconds
      type: int
      returned: success
    display_name:
      description: Display name of the token
      type: str
      returned: success
    entity_id:
      description: Entity ID associated with the token
      type: str
      returned: success
    expire_time:
      description: RFC3339 timestamp when the token expires
      type: str
      returned: success
    explicit_max_ttl:
      description: Explicit max TTL in seconds (0 means none)
      type: int
      returned: success
    id:
      description: The token ID
      type: str
      returned: success
    meta:
      description: Metadata associated with the token
      type: dict
      returned: success
    num_uses:
      description: Number of uses remaining
      type: int
      returned: success
    orphan:
      description: Whether the token is an orphan
      type: bool
      returned: success
    path:
      description: The auth path that created the token
      type: str
      returned: success
    policies:
      description: Policies attached to the token
      type: list
      returned: success
      elements: str
    renewable:
      description: Whether the token is renewable
      type: bool
      returned: success
    ttl:
      description: Remaining TTL in seconds
      type: int
      returned: success
    type:
      description: The type of token (service, batch)
      type: str
      returned: success
raw:
  description: The full JSON response from Vault including the envelope.
  returned: success
  type: dict
"""
