---
name: Integration

on: # yamllint disable-line rule:truthy
  pull_request_target:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - main
      - stable-*

jobs:
  run-integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    env:
      collection_install_path: "/home/runner/.ansible/collections/ansible_collections/hashicorp/vault/"
    strategy:
      fail-fast: false
      matrix:
        ansible-version:
          - stable-2.19
          - stable-2.18
          - devel
        python-version:
          - "3.12"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install jq
        run: python3 -m pip install jq

      - name: Install ansible-core (${{ matrix.ansible-version }})
        run: python3 -m pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible-version }}.tar.gz --disable-pip-version-check

      - name: Install collection test dependencies
        run: python3 -m pip install -r test-requirements.txt

      - name: Build and install the collection
        run: ansible-galaxy collection install . --force

      - name: Request token
        id: create-token
        run: >-
          curl -s --header "X-Vault-Namespace: $VAULT_NAMESPACE"
          --request POST
          --data '{"role_id": "$VAULT_ROLE_ID", "secret_id": "$VAULT_SECRET_ID"}'
          $VAULT_ADDR/v1/auth/approle-integration-tests/login
        shell: bash
        working-directory: "${{ env.collection_install_path }}tests/integration"
        env:
          VAULT_ADDR: "{{ secrets.VAULT_ADDR }}"
          VAULT_NAMESPACE: "{{ secrets.VAULT_NAMESPACE }}"
          VAULT_ROLE_ID: "{{ secrets.VAULT_APPROLE_ROLE_ID }}"
          VAULT_SECRET_ID: "{{ secrets.VAULT_APPROLE_SECRET_ID }}"

      - name: Render integration_config.yml from template
        shell: bash
        run: ansible -m ansible.builtin.template -a 'src=integration_config.yml.j2 dest=integration_config.yml' localhost
        working-directory: "${{ env.collection_install_path }}tests/integration"
        env:
          VAULT_ADDR: "${{ secrets.VAULT_ADDR }}"
          VAULT_NAMESPACE: "${{ secrets.VAULT_NAMESPACE }}"

      - name: Run integration tests
        uses: ansible-network/github_actions/.github/actions/ansible_test_integration@main
        with:
          collection_path: "${{ env.collection_install_path }}"
          python_version: "${{ matrix.python-version }}"
          ansible_version: "${{ matrix.ansible-version }}"
