---
name: Integration

on: # yamllint disable-line rule:truthy
  pull_request_target:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - main
      - stable-*

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    env:
      source: "./"
    strategy:
      fail-fast: false
      matrix:
        ansible-version:
          - stable-2.19
          - stable-2.18
          - devel
        python-version:
          - "3.12"
    name: "integration-tests-${{ matrix.ansible-version }}-${{ matrix.python-version }}"
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.source }}
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ansible-core (${{ matrix.ansible-version }})
        run: python3 -m pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible-version }}.tar.gz --disable-pip-version-check

      # Install the source collection
      - name: Build and install collection
        id: install-collection
        uses: ansible-network/github_actions/.github/actions/build_install_collection@main
        with:
          install_python_dependencies: true
          source_path: ${{ env.source }}

      - name: Set up git
        run: |
          git config --global user.email gha@localhost
          git config --global user.name "Github Actions"
        shell: bash

      - name: Create Hashicorp vault token for test session
        id: create-token
        run: |
          token=`curl -s --header "X-Vault-Namespace: $VAULT_NAMESPACE" --request POST --data '{"role_id": "$VAULT_ROLE_ID", "secret_id": "$VAULT_SECRET_ID"}' $VAULT_ADDR/v1/auth/approle/login | jq -r '.auth.client_token'`; echo "generated_token='$params'" >> ${GITHUB_OUTPUT}
        shell: bash
        env:
          VAULT_ADDR: "{{ secrets.VAULT_ADDR }}"
          VAULT_NAMESPACE: "{{ secrets.VAULT_NAMESPACE }}"
          VAULT_ROLE_ID: "{{ secrets.VAULT_APPROLE_ROLE_ID }}"
          VAULT_SECRET_ID: "{{ secrets.VAULT_APPROLE_SECRET_ID }}"

      - name: Run integration tests
        uses: ansible-network/github_actions/.github/actions/ansible_test_integration@main
        with:
          collection_path: ${{ steps.install-collection.outputs.collection_path }}
          python_version: "${{ matrix.python-version }}"
          ansible_version: "${{ matrix.ansible-version }}"
          ansible_test_environment: |
            VAULT_TOKEN={{ steps.create-token.outputs.generated_token }}
            VAULT_ADDR={{ secrets.VAULT_ADDR }}
