---
# vars_files: [vars.yml]
#
# name: test-static-role
# mount_path: database
# config:
#   db_name: my-postgres
#   username: vault-user
#   credential_type: password
#   rotation_period: "24h"

- name: Read or list Vault database static roles
  hashicorp.vault.vault_database_static_role_info:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    mount_path: "{{ mount_path }}"
    name: "{{ name }}"
  register: result

- name: Verify return matches contract
  ansible.builtin.assert:
    that:
      - result is not changed
      - (config | hashicorp.vault.vault_config_match(result.data)).match
    fail_msg: "Contract violation: {{ (config | hashicorp.vault.vault_config_match(result.data)).mismatches | to_json }}"
